services:
  reelclips-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reelclips-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production